# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-05-03 11:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20170402_1819'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensorgroup2',
            old_name='Sensorgroup2_date',
            new_name='Sensor_date',
        ),
        migrations.RenameField(
            model_name='sensorgroup2',
            old_name='Sensorgroup2_name',
            new_name='Sensor_name',
        ),
        migrations.RenameField(
            model_name='sensorgroup2',
            old_name='Sensorgroup2_value',
            new_name='Sensor_value',
        ),
        migrations.RemoveField(
            model_name='sensorgroup2',
            name='Sensorgroup2_group',
        ),
    ]
